apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-microservices-deploy
  labels:
    app: python-microservices
    test: test
  annotations:
    fluxcd.io/tag.example-app: semver:~1.0
    fluxcd.io/automated: 'true'
spec:
  selector:
    matchLabels:
      app: python-microservices
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: python-microservices
    spec:
      containers:
      - name: cfrontend-app
        image: ajitha1234/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      - name: cuserservice-app
        image: ajitha1234/userservice:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      - name: corderservice-app
        image: ajitha1234/orderservice:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5002
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      - name: cproductservice-app
        image: ajitha1234/productservice:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5003
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
