apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-db
  labels:
    app: rapdev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rapdev
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rapdev
    spec:
      containers:
        - name: product-db
          image: mysql:8
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: productdb-vol
          env:
            - name: MYSQL_DATABASE
              value: product
            - name: MYSQL_PASSWORD
              value: pfm_2020
            - name: MYSQL_ROOT_PASSWORD
              value: pfm_dc_2020
            - name: MYSQL_USER
              value: cloudacademy
      restartPolicy: Always
      volumes:
        - name: productdb-vol
          persistentVolumeClaim:
            claimName: productdb-vol
---
apiVersion: v1
kind: Service
metadata:
    labels:
        app: rapdev
    name: product-db
spec:
    ports:
        - name: product-db
          port: 32001
          targetPort: 3306
    selector:
        app: rapdev
    clusterIP: None
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: product-db
spec:
  rules:
    - http:
        paths:
          - path: /product
            pathType: Prefix
            backend:
              service:
                name: product-db
                port:
                  number: 8080
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: productdb-vol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-product-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"