apiVersion: apps/v1
kind: Deployment
metadata:
  name: cproduct-service
  labels:
    app: rapdev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rapdev
  template:
    metadata:
      labels:
        app: rapdev
    spec:
      containers:
        - name: cproduct-service
          image: vinaysj/product-api
          ports:
            - containerPort: 5002
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
    labels:
        app: rapdev
    name: cproduct-service
spec:
    ports:
        - name: cproduct-service
          port: 5002
          targetPort: 5002
    selector:
        app: rapdev
    clusterIP: None
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cproduct-service
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cproduct-service
                port:
                  number: 8080

status: {}

