apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-db
  labels:
    app: rapdev
#  namespace: rapdev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rapdev
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rapdev
    spec:
      containers:
        - name: user-db
          image: mysql:8
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: userdb-vol
          env:
            - name: MYSQL_DATABASE
              value: user
            - name: MYSQL_PASSWORD
              value: pfm_2020
            - name: MYSQL_ROOT_PASSWORD
              value: pfm_dc_2020
            - name: MYSQL_USER
              value: cloudacademy
      restartPolicy: Always
      volumes:
        - name: userdb-vol
          persistentVolumeClaim:
            claimName: userdb-vol
---
apiVersion: v1
kind: Service
metadata:
#    namespace: rapdev
    labels:
        app: rapdev
    name: user-db
spec:
    ports:
        - name: user-db
          port: 32000
          targetPort: 3306
    selector:
        app: rapdev
    clusterIP: None
#    type: NodePort
#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: user-db
##  namespace: rapdev
#spec:
#  rules:
#    - http:
#        paths:
#          - path: /user
#            pathType: Prefix
#            backend:
#              service:
#                name: user-db
#                port:
#                  number: 8080
#status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: userdb-vol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-user-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"